name: Docker build and push
on:
  workflow_dispatch:
jobs:
  docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ github.repository_owner	}}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile-release
          build-args: |
            REPO=sigoden/proxyfor
            VER=v0.3.0
          platforms: |
            linux/amd64
            linux/arm64
            linux/386
            linux/arm/v7
          push: false
          tags: sigoden/proxyfor:latest
