name: Manual trigger
on:
  workflow_dispatch:
jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: windows-latest
    steps:

    - name: Install Rust Toolchain Components
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross
      if: matrix.use-cross
      uses: taiki-e/install-action@v2
      with:
        tool: cross

    - uses: actions/checkout@v3
      with:
        repository: sigoden/aichat

    - name: Setup upterm session
      uses: mxschmitt/action-tmate@v3