name: Test Setup Create
on:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup argc 
      uses: extractions/setup-crate@v1 
      with:
        owner: sigoden
        name: argc -h
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # avoid rate limiting errors
    - name: Test
      run: argc -V
      shell: bash